### ISSUE TITLE
Error: The target entry-point "ngx-video-timeline" has missing dependencies:  - dayjs

### ISSUE THREAD

**Issue by BenRacicot** [lenonMax/ngx-video-timeline#1]
Hello,

Just thought I'd try out your cool project! After setting up as the NPM page describes I get the error.

```
Error: The target entry-point "ngx-video-timeline" has missing dependencies: - dayjs
```

**Comment by Howjune** [comment]
I'm sorry for not being able to reply in time.I will fix it later.

**Comment by Howjune** [comment]
I chekced the code and could run it.Could you please try again?

**Comment by lenonMax** [comment]
The issue is inactive. Now close it.
