### ISSUE TITLE
Cannot find module 'projects/timeline/src/lib/timeline.component' 

### ISSUE THREAD

**Issue by prarthanashr04** [lenonMax/ngx-video-timeline#28]
Getting Error 'Cannot find module 'projects/timeline/src/lib/timeline.component' and Cannot find module 'projects/timeline/src/lib/timeline.module''. Even after cloning from this repository.

**Comment by lenonMax** [comment]
@prarthanashr04 I'm sorry for the delay. I have changed the absolute path to node_modules. Would it be possible for you to try again?

**Comment by prarthanashr04** [comment]
Yes , will do . Thanks
